services:
  app:
    build:
      context: .
      target: development
    container_name: springsecurity-jwt-app
    working_dir: /app
    volumes:
      - ./:/app/
    env_file:
      - ./mysql/.env
    ports:
      - "8080:8080"
      - "8000:8000"
    tty: true
    depends_on:
      - mysql
  mysql:
    build: ./mysql
    container_name: springsecurity-jwt-mysql
    volumes:
      - springsecurity-jwt-mysql_data:/var/lib/mysql
      - springsecurity-jwt-mysql_log:/var/log/mysql
    env_file:
      - ./mysql/.env
    ports:
      - "3306:3306"

volumes:
  springsecurity-jwt-mysql_data:
    external: true
  springsecurity-jwt-mysql_log:
    external: true
